services:
  postgres:
    image: postgres:16
    container_name: quickchat-db
    environment:
      POSTGRES_DB: quickchat
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"