server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://ep-red-band-aq70gk90-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_BJgP61kVXNDr
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true